spring:
  application:
    name: master-data-migrator


migration:
  source-datasource:
      host: master-data-mysql-master-data-migrator.i.aivencloud.com
      port: 10536
      database: visa_dev
      username: avnadmin
      password: AVNS_ChgdFdRuEmAg8DeULcM

  target-datasource:
      host: master-data-mysql-master-data-migrator.i.aivencloud.com
      port: 10536
      database: visa_prod
      username: avnadmin
      password: AVNS_ChgdFdRuEmAg8DeULcM